#!/usr/bin/zsh
set -e
sudo apt update
sudo apt upgrade
sudo apt full-upgrade
sudo apt autoremove
sudo apt autoclean
sudo apt clean
flatpak update

#sudo chown root: /usr/local/bin/SCRIPTNAME
# sudo chmod 755 /usr/local/bin/SCRIPTNAME